"""Authentication layer: magic links and JWT sessions."""

from __future__ import annotations

import hashlib
import re
import secrets
from datetime import datetime, timedelta, timezone
from typing import Any

import jwt
from fastapi import HTTPException, Request, Response

from src.web.config import get_settings
from src.web.models.user import Connector, User, UserRole
from src.web.services.user_storage import UserStorage

ALGORITHM = "HS256"
MAGIC_LINK_EXPIRE_MINUTES = 15
SESSION_EXPIRE_HOURS = 24
COOKIE_NAME = "session"

# Magic link tokens are generated by secrets.token_urlsafe(32) which produces
# exactly 43 URL-safe base64 characters (letters, digits, '-' and '_').
# The regex enforces this format on every incoming token before it is used.
MAGIC_LINK_TOKEN_RE = re.compile(r"^[A-Za-z0-9\-_]{43}$")
MAGIC_LINK_TOKEN_LENGTH = 43


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _hash_token(token: str) -> str:
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def _random_token(n: int = 32) -> str:
    return secrets.token_urlsafe(n)


def create_magic_link(email: str, storage: UserStorage | None = None) -> tuple[str, str]:
    """Create a single-use magic link token and return (token, url)."""
    if storage is None:
        storage = UserStorage()
    user = storage.get_user_by_email(email)
    if user is None:
        raise HTTPException(status_code=403, detail="Neplatný email.")
    if user.role != UserRole.NEW_ADMIN and not user.is_active:
        # Pending new_admin can receive a magic link even while inactive.
        raise HTTPException(status_code=403, detail="Účet není aktivní.")

    token = _random_token()
    token_hash = _hash_token(token)
    expires_at = _now() + timedelta(minutes=MAGIC_LINK_EXPIRE_MINUTES)
    storage.save_magic_link(token_hash, email, expires_at)

    settings = get_settings()
    base_url = settings.APP_BASE_URL.rstrip("/")
    url = f"{base_url}/auth/magic-link-redirect?token={token}"
    return token, url


def register_user(email: str, storage: UserStorage | None = None) -> tuple[User, str, str]:
    """Create a pending new_admin user and return (user, token, url).

    The user is created inactive with role ``new_admin``. The first magic-link
    click activates the account and promotes the role to ``admin``.
    """
    if storage is None:
        storage = UserStorage()
    if not get_settings().REGISTRATION_ENABLED:
        raise HTTPException(status_code=403, detail="Registrace není povolena.")
    existing = storage.get_user_by_email(email)
    if existing is not None:
        raise HTTPException(status_code=409, detail="Uživatel s tímto emailem již existuje.")

    # New admin gets a copy of the default (.env) connector.
    connector = _default_connector_from_settings()
    connector.name = email
    created_connector = storage.create_connector(connector)
    user = storage.create_user(
        email=email,
        role=UserRole.NEW_ADMIN,
        connector_id=created_connector.id,
    )
    token, url = create_magic_link(email, storage)
    return user, token, url


def _default_connector_from_settings() -> Connector:
    settings = get_settings()
    return Connector(
        name="Default (.env)",
        db_host=settings.DB_HOST,
        db_port=settings.DB_PORT,
        db_name=settings.DB_NAME,
        db_user=settings.DB_USER,
        db_password=settings.DB_PASSWORD,
        db_driver=settings.DB_DRIVER,
        view_discovery_mode=settings.VIEW_DISCOVERY_MODE,
        api_tenant=settings.API_TENANT,
        api_key=settings.API_KEY or "",
        api_key_header=settings.API_KEY_HEADER,
        api_allowed_ips=settings.API_ALLOWED_IPS,
        api_max_requests_per_minute=settings.API_MAX_REQUESTS_PER_MINUTE,
    )


def _validate_magic_link_token(token: str) -> str:
    """Reject any magic link token that does not match the expected format.

    Only URL-safe base64 characters of the exact length produced by
    ``secrets.token_urlsafe(32)`` are accepted. This prevents pathological
    or malformed input from ever reaching the database lookup.
    """
    if not token or not MAGIC_LINK_TOKEN_RE.match(token):
        raise HTTPException(status_code=400, detail="Neplatný nebo expirovaný odkaz.")
    return token


def consume_magic_link(token: str, storage: UserStorage | None = None) -> str:
    """Validate magic link token and create a session JWT.

    If the user is a pending ``new_admin``, activate them and promote the role
    to ``admin`` on first use.
    """
    token = _validate_magic_link_token(token)
    if storage is None:
        storage = UserStorage()
    token_hash = _hash_token(token)
    link = storage.use_magic_link(token_hash)
    if link is None:
        raise HTTPException(status_code=400, detail="Neplatný nebo expirovaný odkaz.")
    user = storage.get_user_by_email(link["email"])
    if user is None:
        raise HTTPException(status_code=403, detail="Účet nebyl nalezen.")
    if user.role == UserRole.NEW_ADMIN:
        storage.activate_new_admin(user.id)
        user = storage.get_user_by_id(user.id)
    if user is None or not user.is_active:
        raise HTTPException(status_code=403, detail="Účet nebyl nalezen nebo není aktivní.")
    session_token = create_session_token(user)
    storage.save_session(_hash_token(session_token), user.id)
    return session_token


def create_session_token(user: User) -> str:
    """Return signed JWT for the user."""
    settings = get_settings()
    now = _now()
    payload = {
        "sub": str(user.id),
        "email": user.email,
        "role": user.role.value,
        "connector_id": user.connector_id,
        "iat": now,
        "exp": now + timedelta(hours=SESSION_EXPIRE_HOURS),
    }
    return jwt.encode(payload, settings.JWT_SECRET, algorithm=ALGORITHM)



def set_session_cookie(response: Response, token: str, *, secure: bool | None = None) -> None:
    if secure is None:
        settings = get_settings()
        secure = not settings.LOCALHOST_MODE
    response.set_cookie(
        key=COOKIE_NAME,
        value=token,
        httponly=True,
        secure=secure,
        samesite="lax",
        path="/",
        max_age=int(timedelta(hours=SESSION_EXPIRE_HOURS).total_seconds()),
    )


def clear_session_cookie(response: Response) -> None:
    response.delete_cookie(key=COOKIE_NAME)


def _hash_token(token: str) -> str:
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def _decode_token(token: str) -> dict[str, Any]:
    try:
        return jwt.decode(token, get_settings().JWT_SECRET, algorithms=[ALGORITHM])
    except jwt.ExpiredSignatureError as exc:
        raise HTTPException(status_code=401, detail="Session expired") from exc
    except jwt.InvalidTokenError as exc:
        raise HTTPException(status_code=401, detail="Invalid session") from exc


def get_current_user(request: Request) -> User:
    token = request.cookies.get(COOKIE_NAME)
    if not token:
        raise HTTPException(status_code=401, detail="Not authenticated")
    storage = UserStorage()
    token_hash = _hash_token(token)
    if not storage.is_session_valid(token_hash):
        raise HTTPException(status_code=401, detail="Session revoked")
    payload = _decode_token(token)
    user_id = payload.get("sub")
    user = storage.get_user_by_id(int(user_id)) if user_id else None
    if user is None or not user.is_active:
        raise HTTPException(status_code=401, detail="User not found or inactive")
    return user


def get_current_user_optional(request: Request) -> User | None:
    """Return the current user if authenticated, otherwise None."""
    try:
        return get_current_user(request)
    except HTTPException:
        return None


def get_current_admin(request: Request) -> User:
    user = get_current_user(request)
    if user.role != UserRole.ADMIN:
        raise HTTPException(status_code=403, detail="Admin access required")
    return user


def require_user(request: Request) -> User:
    return get_current_user(request)


def require_admin(request: Request) -> User:
    return get_current_admin(request)
